FROM python:3.9-slim-buster

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends
build-essential
libpq-dev

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ /app/src
COPY wsgi.py .

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "src.app:app"]