FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json vite.config.js ./
RUN npm install

COPY src/front/ ./src/front/
COPY public/ ./public/

RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]