"""empty message

Revision ID: 01004f40f1dc
Revises: aa41d6350c18
Create Date: 2021-04-30 01:50:40.442732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01004f40f1dc'
down_revision = 'aa41d6350c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cantones', 'id_provincias',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cantones', 'id_provincias',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
