"""empty message

Revision ID: 022cbdf1474e
Revises: 6f5641a0cd72
Create Date: 2025-06-22 14:57:48.645238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022cbdf1474e'
down_revision = '6f5641a0cd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
