"""empty message

Revision ID: 0313d8ce4903
Revises: ef62170ac27a
Create Date: 2023-12-17 02:01:54.691134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0313d8ce4903'
down_revision = 'ef62170ac27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
