"""tarea vinculada a gasto

Revision ID: 0777d42c751e
Revises: 30231e867725
Create Date: 2025-05-27 11:33:10.608352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0777d42c751e'
down_revision = '30231e867725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarea_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tareas', ['tarea_id'], ['id'])

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completada', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.alter_column('evento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('evento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('completada')

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tarea_id')

    # ### end Alembic commands ###
