"""empty message

Revision ID: 0b67aef305cd
Revises: 0763d677d453
Create Date: 2025-10-16 22:32:25.082292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b67aef305cd'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=400), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='experiencelevelenum'), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id_mentor', sa.Integer(), nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_mentor'], ['mentor_profile.id'], ),
    sa.ForeignKeyConstraint(['id_student'], ['student_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentor_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevelenum'), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_profile_id'], ['mentor_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentoring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('mentor_profile_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='statusenum'), nullable=False),
    sa.Column('pricing_topic', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_profile_id'], ['mentor_profile.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['mentor_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentoring_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Boolean(), nullable=False),
    sa.Column('ranking', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentoring_id'], ['mentoring.id'], ),
    sa.ForeignKeyConstraint(['reviewed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['password'])
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['avatar'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')
        batch_op.drop_column('avatar')
        batch_op.drop_column('name')
        batch_op.drop_column('username')

    op.drop_table('review')
    op.drop_table('mentoring')
    op.drop_table('mentor_topic')
    op.drop_table('comments')
    op.drop_table('student_profile')
    op.drop_table('mentor_profile')
    # ### end Alembic commands ###
