"""empty message

<<<<<<<< HEAD:migrations/versions/0d876ddf9401_.py
<<<<<<<< HEAD:migrations/versions/0d876ddf9401_.py
Revision ID: 0d876ddf9401
Revises: 
Create Date: 2025-07-27 11:40:01.836043
========
Revision ID: 9fd7e6d099f9
Revises: 
Create Date: 2025-07-27 10:33:36.904431
>>>>>>>> b32f67e (migrations/versions/04dddaac805e_.py -> migrations/versions/9fd7e6d099f9_.py):migrations/versions/9fd7e6d099f9_.py
========
Revision ID: 9fd7e6d099f9
Revises: 
Create Date: 2025-07-27 10:33:36.904431
>>>>>>>> b32f67e (migrations/versions/04dddaac805e_.py -> migrations/versions/9fd7e6d099f9_.py):migrations/versions/9fd7e6d099f9_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/0d876ddf9401_.py
<<<<<<<< HEAD:migrations/versions/0d876ddf9401_.py
revision = '0d876ddf9401'
========
revision = '9fd7e6d099f9'
>>>>>>>> b32f67e (migrations/versions/04dddaac805e_.py -> migrations/versions/9fd7e6d099f9_.py):migrations/versions/9fd7e6d099f9_.py
========
revision = '9fd7e6d099f9'
>>>>>>>> b32f67e (migrations/versions/04dddaac805e_.py -> migrations/versions/9fd7e6d099f9_.py):migrations/versions/9fd7e6d099f9_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sueldo', sa.Float(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('emoji', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gasto')
    op.drop_table('user')
    # ### end Alembic commands ###
