"""empty message

Revision ID: 0dd6a00fdcbf
Revises: 
Create Date: 2025-07-17 01:50:00.992727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd6a00fdcbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicio',
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('name_service', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id_service')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('identificacion', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=12), nullable=False),
    sa.Column('telefono', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('foto_usuario', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Enum('MECANICO', 'CLIENTE', name='rol_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('vehiculos',
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=8), nullable=False),
    sa.Column('marca', sa.String(length=15), nullable=False),
    sa.Column('modelo', sa.String(length=15), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_vehiculo'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('orden_de_trabajo',
    sa.Column('id_ot', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('estado_servicio', sa.Enum('INGRESADO', 'EN_PROCESO', 'FINALIZADO', name='estado_orden'), nullable=False),
    sa.Column('fecha_final', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.Column('mecanico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mecanico_id'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_ot')
    )
    op.create_table('auxOrdenServicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_de_trabajo.id_ot'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id_service'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auxOrdenServicio')
    op.drop_table('orden_de_trabajo')
    op.drop_table('vehiculos')
    op.drop_table('user')
    op.drop_table('servicio')
    # ### end Alembic commands ###
