"""empty message

Revision ID: 1466af5e8f40
Revises: cd73d3e1f8ee
Create Date: 2025-10-28 02:33:06.476454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1466af5e8f40'
down_revision = 'cd73d3e1f8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=True))
        batch_op.alter_column('specialty',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('work_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['license_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('work_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('specialty',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('phone_number')
        batch_op.drop_column('license_number')

    # ### end Alembic commands ###
