"""empty message

Revision ID: 15366cce7eb8
Revises: 
Create Date: 2024-11-30 01:04:26.944026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15366cce7eb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_token_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Email_Autorizado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('isRegistered', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=70), nullable=True),
    sa.Column('grado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudiante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('representante_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grado_id'], ['grado.id'], ),
    sa.ForeignKeyConstraint(['representante_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'apellido', 'representante_id', name='estudiante_representante_unique')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docente_materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=True),
    sa.Column('id_materia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_docente', 'id_materia', name='docente_materia_unique')
    )
    op.create_table('evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('finalizada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['docente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiante.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calificacion')
    op.drop_table('evaluacion')
    op.drop_table('docente_materias')
    op.drop_table('messages')
    op.drop_table('estudiante')
    op.drop_table('docente')
    op.drop_table('user')
    op.drop_table('materia')
    op.drop_table('Email_Autorizado')
    op.drop_table('role')
    op.drop_table('grado')
    op.drop_table('blocked_token_list')
    # ### end Alembic commands ###
