"""empty message

Revision ID: 1b86d4d51db3
Revises: 79139ba2b70f
Create Date: 2024-02-04 16:46:57.190591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b86d4d51db3'
down_revision = '79139ba2b70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('event_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_email'], ['email'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
