"""empty message

Revision ID: 21f5540bab2c
Revises: 
Create Date: 2025-09-20 16:17:04.733283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f5540bab2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('security_question', sa.String(length=255), nullable=True),
    sa.Column('jpeg', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('airbnb_address', sa.String(length=255), nullable=False),
    sa.Column('airbnb_zipcode', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='fk_listings_current_booking', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('airbnb_guest_first_name', sa.String(length=120), nullable=True),
    sa.Column('airbnb_guest_last_name', sa.String(length=120), nullable=True),
    sa.Column('airbnb_checkin', sa.Date(), nullable=True),
    sa.Column('airbnb_checkout', sa.Date(), nullable=True),
    sa.Column('airbnb_guestpic_url', sa.String(length=500), nullable=True),
    sa.Column('airbnb_guestpic', sa.LargeBinary(), nullable=True),
    sa.Column('reservation_url', sa.String(length=500), nullable=True),
    sa.Column('phone_last4', sa.String(length=4), nullable=True),
    sa.Column('needs_manual_details', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(airbnb_checkin IS NULL OR airbnb_checkout IS NULL) OR (airbnb_checkout >= airbnb_checkin)', name='ck_booking_checkout_after_checkin'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'google_calendar_id', name='uq_booking_listing_googleid')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_google_calendar_id'), ['google_calendar_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_google_calendar_id'))

    op.drop_table('bookings')
    op.drop_table('listings')
    op.drop_table('users')
    # ### end Alembic commands ###
