"""empty message

Revision ID: 249eb81e69ab
Revises: f19ac3688509
Create Date: 2025-06-06 10:55:06.596286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249eb81e69ab'
down_revision = 'f19ac3688509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_items', schema=None) as batch_op:
        batch_op.alter_column('calorias',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('proteinas',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('grasas',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('carbohidratos',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('meal_momento',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('muscle_group',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('series',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('repeticiones',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_items', schema=None) as batch_op:
        batch_op.alter_column('repeticiones',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('series',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('muscle_group',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cantidad',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('meal_momento',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('carbohidratos',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('grasas',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('proteinas',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('calorias',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
