"""Agregar descripcion

Revision ID: 34628c965305
Revises: 146a6f384f19
Create Date: 2025-05-27 17:00:40.810677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34628c965305'
down_revision = '146a6f384f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
