"""empty message

Revision ID: 34bb5ed7ff21
Revises: 6978a9b0df47
Create Date: 2025-04-07 10:20:10.611224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bb5ed7ff21'
down_revision = '6978a9b0df47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dirección', sa.String(length=255), nullable=True))
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('dirección')

    # ### end Alembic commands ###
