"""empty message

Revision ID: 35dd433f682c
Revises: a2442d154338
Create Date: 2025-11-13 17:45:21.603812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35dd433f682c'
down_revision = 'a2442d154338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_pedido')
    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('historial_pedido_id_fkey'), type_='foreignkey')
        batch_op.drop_column('pedido_id')

    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.drop_column('comentario')

    with op.batch_alter_table('tienda', schema=None) as batch_op:
        batch_op.alter_column('redes_sociales',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('estilos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tienda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estilos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('redes_sociales',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('resenas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=False))

    with op.batch_alter_table('historial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('historial_pedido_id_fkey'), 'detalles_pedido', ['pedido_id'], ['id'])

    op.create_table('detalles_pedido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('detalles_pedido_producto_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('detalles_pedido_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('detalles_pedido_pkey'))
    )
    # ### end Alembic commands ###
