"""empty message

Revision ID: 3c296f23037f
Revises: bb13f7ff5ea1
Create Date: 2025-04-05 20:27:56.769534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c296f23037f'
down_revision = 'bb13f7ff5ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_hora_inicio', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('fecha_hora_fin', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('google_event_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ultimo_sync', sa.DateTime(), nullable=True))
        batch_op.drop_column('dia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('ultimo_sync')
        batch_op.drop_column('google_event_id')
        batch_op.drop_column('fecha_hora_fin')
        batch_op.drop_column('fecha_hora_inicio')

    # ### end Alembic commands ###
