"""empty message

Revision ID: 3f7334dae1d2
Revises: da53ba445c41
Create Date: 2025-04-07 07:55:22.278760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7334dae1d2'
down_revision = 'da53ba445c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('medication_name', sa.String(length=100), nullable=False),
    sa.Column('dosage_instructions', sa.String(length=300), nullable=True),
    sa.Column('adverse_reactions', sa.String(length=300), nullable=True),
    sa.Column('treatment_start_date', sa.DateTime(), nullable=True),
    sa.Column('treatment_end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_antecedents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('disease', sa.String(length=200), nullable=False),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.drop_column('desencadenante')

    with op.batch_alter_table('blood_pressure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('manual_datetime', sa.DateTime(), nullable=True))

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.alter_column('last_weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('last_height',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('BMI',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    with op.batch_alter_table('glucose', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('manual_datetime', sa.DateTime(), nullable=True))
        batch_op.alter_column('glucose',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('height', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('manual_datetime', sa.DateTime(), nullable=True))
        batch_op.alter_column('height',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('pulse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('manual_datetime', sa.DateTime(), nullable=True))

    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('manual_datetime', sa.DateTime(), nullable=True))
        batch_op.alter_column('weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('manual_datetime')
        batch_op.drop_column('comments')

    with op.batch_alter_table('pulse', schema=None) as batch_op:
        batch_op.drop_column('manual_datetime')
        batch_op.drop_column('comments')

    with op.batch_alter_table('height', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('manual_datetime')
        batch_op.drop_column('comments')

    with op.batch_alter_table('glucose', schema=None) as batch_op:
        batch_op.alter_column('glucose',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('manual_datetime')
        batch_op.drop_column('comments')

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.alter_column('BMI',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('last_height',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('last_weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('blood_pressure', schema=None) as batch_op:
        batch_op.drop_column('manual_datetime')
        batch_op.drop_column('comments')

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desencadenante', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    op.drop_table('personal_antecedents')
    op.drop_table('medications')
    # ### end Alembic commands ###
