"""empty message

Revision ID: 400825a5cadb
Revises: 
Create Date: 2025-05-28 15:28:16.722707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400825a5cadb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('acepta_colaboradores', sa.Boolean(), nullable=False),
    sa.Column('invitados', sa.String(length=500), nullable=True),
    sa.Column('max_invitados', sa.Integer(), nullable=True),
    sa.Column('tipo_actividad', sa.String(length=100), nullable=True),
    sa.Column('vestimenta', sa.String(length=100), nullable=True),
    sa.Column('servicios', sa.String(length=255), nullable=True),
    sa.Column('recursos', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('aceptado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('asignado_a', sa.Integer(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(), nullable=True),
    sa.Column('etiqueta', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos')
    op.drop_table('tareas')
    op.drop_table('participantes')
    op.drop_table('invitaciones')
    op.drop_table('eventos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
