"""empty message

Revision ID: 44f02b04240f
Revises: 7f1e2d0ae1a4
Create Date: 2025-11-13 13:26:13.934157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f02b04240f'
down_revision = '7f1e2d0ae1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('productos_imagenes_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('productos_imagenes_key'), ['imagenes'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
