"""empty message

Revision ID: 45095bf358b8
Revises: bb937043aef4
Create Date: 2025-10-15 18:51:52.162620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45095bf358b8'
down_revision = 'bb937043aef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
