"""empty message

Revision ID: 53b48df1b7bd
Revises: 553e57465e8a
Create Date: 2025-04-09 08:16:03.000690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b48df1b7bd'
down_revision = '553e57465e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente_servicio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_servicio',
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('servicio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='cliente_servicio_cliente_id_fkey'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], name='cliente_servicio_servicio_id_fkey'),
    sa.PrimaryKeyConstraint('cliente_id', 'servicio_id', name='cliente_servicio_pkey')
    )
    # ### end Alembic commands ###
