"""empty message

Revision ID: 566b35bdd172
Revises: 482c5928f1b9
Create Date: 2025-04-03 13:55:03.318874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566b35bdd172'
down_revision = '482c5928f1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_hora', sa.DateTime(), nullable=False))

    with op.batch_alter_table('negocio', schema=None) as batch_op:
        batch_op.drop_constraint('negocio_nombre_negocio_key', type_='unique')

    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('negocio', schema=None) as batch_op:
        batch_op.create_unique_constraint('negocio_nombre_negocio_key', ['nombre_negocio'])

    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_column('fecha_hora')

    # ### end Alembic commands ###
