"""empty message

Revision ID: 574f5b4270c9
Revises: 
Create Date: 2025-07-28 18:13:48.023485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574f5b4270c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=27), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sueldo', sa.Float(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('emoji', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gasto')
    op.drop_table('user')
    # ### end Alembic commands ###
