"""empty message

Revision ID: 57561960a0c5
Revises: 6a46316c7cb3
Create Date: 2025-05-07 14:55:24.074779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57561960a0c5'
down_revision = '6a46316c7cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
