"""Add geometry field to Field

Revision ID: 5a0984d7dc38
Revises: 07900b802d7b
Create Date: 2025-04-19 15:13:24.863247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a0984d7dc38'
down_revision = '07900b802d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geometry', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('geometry')

    # ### end Alembic commands ###
