"""empty message

Revision ID: 5cf725964086
Revises: e882aaa7e01e
Create Date: 2024-11-30 11:31:26.832067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf725964086'
down_revision = 'e882aaa7e01e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('species', sa.Enum('perro', 'gato', 'ave', 'conejo', 'otro', name='species'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('breed', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='genders'), nullable=True),
    sa.Column('color', sa.String(length=15), nullable=True),
    sa.Column('photo_1', sa.String(length=120), nullable=False),
    sa.Column('photo_2', sa.String(length=120), nullable=True),
    sa.Column('photo_3', sa.String(length=120), nullable=True),
    sa.Column('photo_4', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breed'], ['breed.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zone', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('pet_status', sa.Enum('lost', 'find', 'joined', name='petstatus'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('security_question', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('security_question')
        batch_op.drop_column('instagram')
        batch_op.drop_column('facebook')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    op.drop_table('post_description')
    op.drop_table('pet')
    op.drop_table('breed')
    # ### end Alembic commands ###
