"""empty message

Revision ID: 645574359ce4
Revises: 307ff11dc3b1
Create Date: 2025-04-07 08:46:24.473920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645574359ce4'
down_revision = '307ff11dc3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('shop_name')

    # ### end Alembic commands ###
