"""fix relationship foreign keys

Revision ID: 652b72709a3a
Revises: 986a803be618
Create Date: 2025-09-08 23:24:12.835195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652b72709a3a'
down_revision = '986a803be618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airbnb_guest_last_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('airbnb_guestpic_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('reservation_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('phone_last4', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('needs_manual_details', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_bookings_google_calendar_id'), ['google_calendar_id'], unique=False)
        batch_op.create_unique_constraint('uq_booking_listing_googleid', ['listing_id', 'google_calendar_id'])

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_listings_current_booking', 'bookings', ['booking_id'], ['id'], use_alter=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_listings_current_booking', type_='foreignkey')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_booking_listing_googleid', type_='unique')
        batch_op.drop_index(batch_op.f('ix_bookings_google_calendar_id'))
        batch_op.drop_column('needs_manual_details')
        batch_op.drop_column('phone_last4')
        batch_op.drop_column('reservation_url')
        batch_op.drop_column('airbnb_guestpic_url')
        batch_op.drop_column('airbnb_guest_last_name')

    # ### end Alembic commands ###
