"""empty message

Revision ID: 680756b48538
Revises: 1f2673104247
Create Date: 2025-04-29 00:29:00.313092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680756b48538'
down_revision = '1f2673104247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showTitle', sa.String(length=50), nullable=True),
    sa.Column('favorites_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show')
    # ### end Alembic commands ###
