"""empty message

Revision ID: 68834b4047a6
Revises: c0e6e28407ad
Create Date: 2025-10-18 21:44:29.020793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68834b4047a6'
down_revision = 'c0e6e28407ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['avatar'])
        batch_op.create_unique_constraint(None, ['username'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_avatar_key', type_='unique')
        batch_op.drop_constraint('user_username_key', type_='unique')
        batch_op.drop_column('avatar')
        batch_op.drop_column('name')
        batch_op.drop_column('username')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_username_key', ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint('user_avatar_key', ['avatar'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('mentor_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('avatar')
        batch_op.drop_column('name')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
