"""empty message

Revision ID: 68f98650827f
Revises: 590c5a30275a
Create Date: 2025-10-25 19:04:09.003869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f98650827f'
down_revision = '590c5a30275a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_topic', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
