"""empty message

Revision ID: 699e14df4489
Revises: ff0179d23264
Create Date: 2025-04-03 10:10:24.336592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699e14df4489'
down_revision = 'ff0179d23264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fields', schema=None) as batch_op:
        batch_op.drop_column('coordinates')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dni', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rolId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('dni', name='user_dni_key'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    # ### end Alembic commands ###
