"""empty message

Revision ID: 69c4b2b032cd
Revises: 3f7334dae1d2
Create Date: 2025-04-07 14:08:41.464436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69c4b2b032cd'
down_revision = '3f7334dae1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blood_pressure', schema=None) as batch_op:
        batch_op.alter_column('manual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.alter_column('last_weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('last_height',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('BMI',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    with op.batch_alter_table('glucose', schema=None) as batch_op:
        batch_op.alter_column('manual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('height', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.alter_column('manual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('pulse', schema=None) as batch_op:
        batch_op.alter_column('manual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.alter_column('manual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.alter_column('manual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('pulse', schema=None) as batch_op:
        batch_op.alter_column('manual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('height', schema=None) as batch_op:
        batch_op.alter_column('manual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('glucose', schema=None) as batch_op:
        batch_op.alter_column('manual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.alter_column('BMI',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('last_height',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('last_weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('blood_pressure', schema=None) as batch_op:
        batch_op.alter_column('manual_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
