"""empty message

Revision ID: 727b004dfad3
Revises: 8939202cfc94
Create Date: 2025-07-07 22:13:23.316444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727b004dfad3'
down_revision = '8939202cfc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
