"""empty message

Revision ID: 72a24d7559aa
Revises: f702105fd5a0
Create Date: 2025-03-25 15:05:19.999381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a24d7559aa'
down_revision = 'f702105fd5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('specie_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('starship_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vehicle_favorites')
    op.drop_table('starship_favorites')
    op.drop_table('specie_favorites')
    op.drop_table('planet_favorites')
    op.drop_table('person_favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='person_favorites_person_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='person_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='person_favorites_pkey')
    )
    op.create_table('planet_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='planet_favorites_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='planet_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='planet_favorites_pkey')
    )
    op.create_table('specie_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('specie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['specie_id'], ['species.id'], name='specie_favorites_specie_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='specie_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='specie_favorites_pkey')
    )
    op.create_table('starship_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('starship_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['starship_id'], ['starships.id'], name='starship_favorites_starship_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='starship_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='starship_favorites_pkey')
    )
    op.create_table('vehicle_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='vehicle_favorites_user_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='vehicle_favorites_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vehicle_favorites_pkey')
    )
    op.drop_table('favorites')
    op.drop_table('categories')
    # ### end Alembic commands ###
