"""empty message

Revision ID: 755f6151a2f5
Revises: 5f30db2c5536
Create Date: 2025-06-03 22:04:59.447065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755f6151a2f5'
down_revision = '5f30db2c5536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
