"""empty message

Revision ID: 79139ba2b70f
Revises: 0100dd69fc76
Create Date: 2024-02-04 16:02:32.091794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79139ba2b70f'
down_revision = '0100dd69fc76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
