"""empty message

Revision ID: 83fe6c9ba8d4
Revises: 2fb88c4c6ceb
Create Date: 2025-04-08 13:48:31.355418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fe6c9ba8d4'
down_revision = '2fb88c4c6ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
