"""Agrega campo email a invitaciones

Revision ID: 876c5c2b3943
Revises: 400825a5cadb
Create Date: 2025-05-29 11:22:14.216630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876c5c2b3943'
down_revision = '400825a5cadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitaciones', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
