"""empty message

Revision ID: 87770d07ad8d
Revises: 03949f15384d
Create Date: 2025-06-24 04:00:54.021551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87770d07ad8d'
down_revision = '03949f15384d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
