"""empty message

Revision ID: 8b337f9164c8
Revises: 0572e93518ce
Create Date: 2025-04-28 22:54:41.602965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b337f9164c8'
down_revision = '0572e93518ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
