"""empty message

Revision ID: 94ff89d6e45b
Revises: 5ba6d964782b
Create Date: 2025-06-03 22:27:11.080055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ff89d6e45b'
down_revision = '5ba6d964782b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
