"""empty message

Revision ID: 96936baa5bb3
Revises: fe1532a7ae5d
Create Date: 2021-05-10 23:40:23.531455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96936baa5bb3'
down_revision = 'fe1532a7ae5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyme', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pyme', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pyme', type_='foreignkey')
    op.drop_column('pyme', 'id_user')
    # ### end Alembic commands ###
