"""empty message

Revision ID: 99d879560cc2
Revises: b85dceac24a2
Create Date: 2024-03-01 19:57:00.811047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99d879560cc2'
down_revision = 'b85dceac24a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('Student', 'Instructor', name='role'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
