"""empty message

Revision ID: 9a9a7ff26129
Revises: 0763d677d453
Create Date: 2025-08-29 23:31:50.356464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9a7ff26129'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('security_question', sa.String(length=255), nullable=True),
    sa.Column('jpeg', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('airbnb_address', sa.String(length=255), nullable=False),
    sa.Column('airbnb_zipcode', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name='fk_listings_current_booking', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('airbnb_guest_first_name', sa.String(length=120), nullable=True),
    sa.Column('airbnb_checkin', sa.Date(), nullable=True),
    sa.Column('airbnb_checkout', sa.Date(), nullable=True),
    sa.Column('airbnb_guestpic', sa.LargeBinary(), nullable=True),
    sa.CheckConstraint('(airbnb_checkin IS NULL OR airbnb_checkout IS NULL) OR (airbnb_checkout >= airbnb_checkin)', name='ck_booking_checkout_after_checkin'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('bookings')
    op.drop_table('listings')
    op.drop_table('users')
    # ### end Alembic commands ###
