"""empty message

Revision ID: 9b16cb350b7a
Revises: 
Create Date: 2025-08-04 10:31:02.522274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b16cb350b7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=False),
    sa.Column('distribuidora', sa.String(length=20), nullable=False),
    sa.Column('online', sa.Integer(), nullable=False),
    sa.Column('offline', sa.Integer(), nullable=False),
    sa.Column('gamemode', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('games')
    # ### end Alembic commands ###
