"""empty message

Revision ID: 9c77c9e89267
Revises: e3db50fe68da
Create Date: 2024-01-05 18:16:21.007162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c77c9e89267'
down_revision = 'e3db50fe68da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('relese_date', sa.String(length=80), nullable=False),
    sa.Column('poster', sa.String(length=3000), nullable=False),
    sa.Column('description', sa.String(length=3000), nullable=False),
    sa.Column('funny', sa.Boolean(), nullable=False),
    sa.Column('sad', sa.Boolean(), nullable=False),
    sa.Column('couple', sa.Boolean(), nullable=False),
    sa.Column('party', sa.Boolean(), nullable=False),
    sa.Column('action', sa.Boolean(), nullable=False),
    sa.Column('drama', sa.Boolean(), nullable=False),
    sa.Column('family', sa.Boolean(), nullable=False),
    sa.Column('kids', sa.Boolean(), nullable=False),
    sa.Column('animation', sa.Boolean(), nullable=False),
    sa.Column('violence', sa.Boolean(), nullable=False),
    sa.Column('historical', sa.Boolean(), nullable=False),
    sa.Column('epic', sa.Boolean(), nullable=False),
    sa.Column('happy', sa.Boolean(), nullable=False),
    sa.Column('hard_to_watch', sa.Boolean(), nullable=False),
    sa.Column('motivating', sa.Boolean(), nullable=False),
    sa.Column('blockbuster', sa.Boolean(), nullable=False),
    sa.Column('very_famous', sa.Boolean(), nullable=False),
    sa.Column('independent', sa.Boolean(), nullable=False),
    sa.Column('sunday_movie', sa.Boolean(), nullable=False),
    sa.Column('terror', sa.Boolean(), nullable=False),
    sa.Column('christmas', sa.Boolean(), nullable=False),
    sa.Column('halloween', sa.Boolean(), nullable=False),
    sa.Column('white_noise', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_2')
    # ### end Alembic commands ###
