"""empty message

Revision ID: 9d2d7be0f5d0
Revises: f38fc28980d8
Create Date: 2025-04-08 19:39:52.014496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2d7be0f5d0'
down_revision = 'f38fc28980d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles__facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prod_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'productos', ['prod_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles__facturas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prod_id')

    # ### end Alembic commands ###
