"""empty message

Revision ID: a2ea06beb0e6
Revises: 17c719196dbc
Create Date: 2024-01-03 11:04:07.472273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ea06beb0e6'
down_revision = '17c719196dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint('movie_couple_key', type_='unique')
        batch_op.drop_constraint('movie_epic_key', type_='unique')
        batch_op.drop_constraint('movie_etc_key', type_='unique')
        batch_op.drop_constraint('movie_family_key', type_='unique')
        batch_op.drop_constraint('movie_funny_key', type_='unique')
        batch_op.drop_constraint('movie_happy_key', type_='unique')
        batch_op.drop_constraint('movie_sunday_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.create_unique_constraint('movie_sunday_key', ['sunday'])
        batch_op.create_unique_constraint('movie_happy_key', ['happy'])
        batch_op.create_unique_constraint('movie_funny_key', ['funny'])
        batch_op.create_unique_constraint('movie_family_key', ['family'])
        batch_op.create_unique_constraint('movie_etc_key', ['etc'])
        batch_op.create_unique_constraint('movie_epic_key', ['epic'])
        batch_op.create_unique_constraint('movie_couple_key', ['couple'])

    # ### end Alembic commands ###
