"""empty message

Revision ID: a80adf762444
Revises: 
Create Date: 2023-12-16 03:28:23.139804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80adf762444'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicacion',
    sa.Column('idPublicacion', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('apellido', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('comuna', sa.String(length=200), nullable=False),
    sa.Column('rubro', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('idPublicacion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fecha')
    )
    op.create_table('user',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('apellido', sa.String(length=200), nullable=False),
    sa.Column('rut', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('fecha_de_nacimiento', sa.Date(), nullable=True),
    sa.Column('rubro', sa.String(length=200), nullable=True),
    sa.Column('comuna', sa.String(length=200), nullable=True),
    sa.Column('tipoUsuario', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut'),
    sa.UniqueConstraint('telefono')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('publicacion')
    # ### end Alembic commands ###
