"""empty message

Revision ID: aa41d6350c18
Revises: e1a497a1e4f5
Create Date: 2021-04-30 01:48:57.713035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa41d6350c18'
down_revision = 'e1a497a1e4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyme', sa.Column('id_canton', sa.Integer(), nullable=False))
    op.add_column('pyme', sa.Column('id_provincia', sa.Integer(), nullable=False))
    op.drop_constraint('pyme_provincia_fkey', 'pyme', type_='foreignkey')
    op.drop_constraint('pyme_canton_fkey', 'pyme', type_='foreignkey')
    op.create_foreign_key(None, 'pyme', 'cantones', ['id_canton'], ['id'])
    op.create_foreign_key(None, 'pyme', 'provincias', ['id_provincia'], ['id'])
    op.drop_column('pyme', 'provincia')
    op.drop_column('pyme', 'canton')
    op.add_column('user', sa.Column('id_tipo', sa.Integer(), nullable=False))
    op.drop_constraint('user_tipo_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'tiposUsuario', ['id_tipo'], ['id'])
    op.drop_column('user', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tipo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_tipo_fkey', 'user', 'tiposUsuario', ['tipo'], ['id'])
    op.drop_column('user', 'id_tipo')
    op.add_column('pyme', sa.Column('canton', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pyme', sa.Column('provincia', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pyme', type_='foreignkey')
    op.drop_constraint(None, 'pyme', type_='foreignkey')
    op.create_foreign_key('pyme_canton_fkey', 'pyme', 'cantones', ['canton'], ['id'])
    op.create_foreign_key('pyme_provincia_fkey', 'pyme', 'provincias', ['provincia'], ['id'])
    op.drop_column('pyme', 'id_provincia')
    op.drop_column('pyme', 'id_canton')
    # ### end Alembic commands ###
