"""fix relationship foreign keys

Revision ID: b16c80a54b5a
Revises: e11f47df9dc2
Create Date: 2025-09-09 00:17:08.297358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16c80a54b5a'
down_revision = 'e11f47df9dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_listings_current_booking', 'bookings', ['booking_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_listings_current_booking', type_='foreignkey')

    # ### end Alembic commands ###
