"""empty message

Revision ID: b2e3c68b49df
Revises: e781cd9472f1
Create Date: 2025-07-22 19:58:27.799428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e3c68b49df'
down_revision = 'e781cd9472f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('user_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
