"""empty message

Revision ID: b5f8f851872f
Revises: 063523d34453
Create Date: 2024-01-28 17:00:24.525584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f8f851872f'
down_revision = '063523d34453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.drop_column('is_superuser')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('level')

    # ### end Alembic commands ###
