"""empty message

Revision ID: b62ff61f5fd2
Revises: 9d2d7be0f5d0
Create Date: 2025-04-09 08:23:26.277411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62ff61f5fd2'
down_revision = '9d2d7be0f5d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cif_empresa', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('cif_empresa')

    # ### end Alembic commands ###
