"""empty message

Revision ID: bb13f7ff5ea1
Revises: 566b35bdd172
Create Date: 2025-04-03 14:15:15.586108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb13f7ff5ea1'
down_revision = '566b35bdd172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negocio_cif', sa.String(length=15), nullable=False))
        batch_op.drop_constraint('usuarios_negocio_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'negocio', ['negocio_cif'], ['negocio_cif'])
        batch_op.drop_column('negocio_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negocio_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usuarios_negocio_id_fkey', 'negocio', ['negocio_id'], ['id'])
        batch_op.drop_column('negocio_cif')

    # ### end Alembic commands ###
