"""empty message

Revision ID: c1691efc1121
Revises: 9851e292a51a
Create Date: 2023-09-15 02:37:23.420387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1691efc1121'
down_revision = '9851e292a51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institutional_user')
    op.drop_table('trackers')
    op.drop_table('scholarship')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('is_active')

    op.create_table('scholarship',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('scholarship_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('scholarship_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('institution', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('deadline', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('modality', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('coverage', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=800), autoincrement=False, nullable=False),
    sa.Column('url_to', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('professional_field', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scholarship_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('trackers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scholarship_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarship.id'], name='trackers_scholarship_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='trackers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trackers_pkey')
    )
    op.create_table('institutional_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('institutional_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='institutional_user_pkey'),
    sa.UniqueConstraint('email', name='institutional_user_email_key'),
    sa.UniqueConstraint('institutional_name', name='institutional_user_institutional_name_key')
    )
    # ### end Alembic commands ###
