"""empty message

Revision ID: c3949545817b
Revises: 15ac61631a67
Create Date: 2024-02-14 18:27:56.449830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3949545817b'
down_revision = '15ac61631a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=False))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('category')
        batch_op.drop_column('city')
        batch_op.drop_column('venue')

    # ### end Alembic commands ###
