"""empty message

Revision ID: c52848fcf70d
Revises: 
Create Date: 2025-08-04 09:15:24.678469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52848fcf70d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('vehicle', sa.Boolean(), nullable=False),
    sa.Column('coordenates', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vehicle_consume_km', sa.Float(precision=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coordenates'),
    sa.UniqueConstraint('email')
    )
    op.create_table('oferta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_comprador', sa.Integer(), nullable=True),
    sa.Column('id_vendedor', sa.Integer(), nullable=False),
    sa.Column('esta_realizada', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.String(length=600), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('coordenates_vendedor', sa.String(length=120), nullable=False),
    sa.Column('coordenates_comprador', sa.String(length=120), nullable=True),
    sa.Column('precio_ud', sa.Integer(), nullable=True),
    sa.Column('ud', sa.String(length=200), nullable=False),
    sa.Column('img_cosecha', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coordenates_comprador'], ['user.coordenates'], ),
    sa.ForeignKeyConstraint(['coordenates_vendedor'], ['user.coordenates'], ),
    sa.ForeignKeyConstraint(['id_comprador'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_vendedor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oferta')
    op.drop_table('user')
    # ### end Alembic commands ###
