"""empty message

Revision ID: ca2a3bb9d8bc
Revises: ba34750de5d6
Create Date: 2024-02-11 16:59:44.807674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca2a3bb9d8bc'
down_revision = 'ba34750de5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('finish_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('liters',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('liters',
               existing_type=sa.Integer(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('finish_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
