"""empty message

Revision ID: cd73d3e1f8ee
Revises: ef5b24ee4ea3
Create Date: 2025-10-24 19:01:11.468866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd73d3e1f8ee'
down_revision = 'ef5b24ee4ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('medical_record')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_record', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
