"""empty message

Revision ID: d06c79c37cc0
Revises: 841fca382b44
Create Date: 2021-05-02 02:27:41.013401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06c79c37cc0'
down_revision = '841fca382b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyme', 'servicio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyme', sa.Column('servicio', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
