"""empty message

Revision ID: d4369418a589
Revises: 244e2e3c2edb
Create Date: 2025-07-17 19:33:59.832371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4369418a589'
down_revision = '244e2e3c2edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oferta', schema=None) as batch_op:
        batch_op.drop_constraint('oferta_id_comprador_key', type_='unique')
        batch_op.drop_constraint('oferta_id_vendedor_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oferta', schema=None) as batch_op:
        batch_op.create_unique_constraint('oferta_id_vendedor_key', ['id_vendedor'])
        batch_op.create_unique_constraint('oferta_id_comprador_key', ['id_comprador'])

    # ### end Alembic commands ###
