"""empty message

Revision ID: d467e9f339a4
Revises: f65b55c1987b
Create Date: 2025-04-16 12:34:55.049228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd467e9f339a4'
down_revision = 'f65b55c1987b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'business', ['business_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###
