"""Añadir is_admin

Revision ID: d4e621522317
Revises: 876cb350dd08
Create Date: 2025-07-31 02:42:24.521384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e621522317'
down_revision = '876cb350dd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ct_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ct_admin', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
