"""empty message

Revision ID: d519be3580dc
Revises: ef64fe5ad678
Create Date: 2025-04-09 19:09:09.087573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd519be3580dc'
down_revision = 'ef64fe5ad678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_logo_url', sa.String(length=500), nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('image_logo_url')

    # ### end Alembic commands ###
