"""empty message

Revision ID: d9645dbc2301
Revises: 1d6800747b29
Create Date: 2025-05-27 13:57:14.367189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9645dbc2301'
down_revision = '1d6800747b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
