"""empty message

Revision ID: da53ba445c41
Revises: ed437196d455
Create Date: 2025-04-03 13:19:29.009678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da53ba445c41'
down_revision = 'ed437196d455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity_enum', sa.Enum('LEVE', 'MODERADA', 'GRAVE', 'MUY_GRAVE', name='severityenum'), nullable=False))
        batch_op.drop_column('severity')

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.alter_column('last_weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('last_height',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.alter_column('BMI',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    with op.batch_alter_table('glucose', schema=None) as batch_op:
        batch_op.alter_column('glucose',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('height', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weight', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('height', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('glucose', schema=None) as batch_op:
        batch_op.alter_column('glucose',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.alter_column('BMI',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('last_height',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('last_weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', postgresql.ENUM('LEVE', 'MODERADA', 'GRAVE', 'MUY_GRAVE', name='severityenum'), autoincrement=False, nullable=False))
        batch_op.drop_column('severity_enum')

    # ### end Alembic commands ###
