"""empty message

Revision ID: dc1fd256366d
Revises: d06c79c37cc0
Create Date: 2021-05-05 00:14:36.653743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1fd256366d'
down_revision = 'd06c79c37cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyme', sa.Column('instagram', sa.String(length=80), nullable=False))
    op.drop_column('pyme', 'instragram')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyme', sa.Column('instragram', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('pyme', 'instagram')
    # ### end Alembic commands ###
