"""empty message

Revision ID: dcc9c71b8a96
Revises: 1466af5e8f40
Create Date: 2025-10-28 02:34:42.196679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc9c71b8a96'
down_revision = '1466af5e8f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('specialty',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('work_days',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('doctors_license_number_key'), type_='unique')
        batch_op.drop_column('license_number')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('license_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('doctors_license_number_key'), ['license_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('work_days',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('specialty',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
