"""empty message

Revision ID: dd88f63d596d
Revises: 
Create Date: 2024-03-04 21:35:39.875883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd88f63d596d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('reviews', sa.String(length=450), nullable=True),
    sa.Column('first_publish_year', sa.Integer(), nullable=True),
    sa.Column('languages', sa.String(length=25), nullable=False),
    sa.Column('publishers', sa.Integer(), nullable=True),
    sa.Column('publisher_places', sa.Integer(), nullable=True),
    sa.Column('typeOfBook', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_name'),
    sa.UniqueConstraint('first_publish_year'),
    sa.UniqueConstraint('title')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=15), nullable=True),
    sa.Column('num_likes', sa.Integer(), nullable=False),
    sa.Column('num_dislikes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('comments')
    op.drop_table('books')
    # ### end Alembic commands ###
