"""empty message

Revision ID: e0140ad61c87
Revises: 80e230ce9b6e
Create Date: 2024-02-19 00:02:31.698150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0140ad61c87'
down_revision = '80e230ce9b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('Student', 'Instructor', name='role'),
               nullable=True)
        batch_op.alter_column('subscription_start_date',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('subscription_start_date',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('Student', 'Instructor', name='role'),
               nullable=False)

    # ### end Alembic commands ###
