"""empty message

Revision ID: e1a497a1e4f5
Revises: f72e3adfa67f
Create Date: 2021-04-30 01:43:20.402173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a497a1e4f5'
down_revision = 'f72e3adfa67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cantones', sa.Column('id_provincias', sa.Integer(), nullable=True))
    op.drop_constraint('cantones_provincias_fkey', 'cantones', type_='foreignkey')
    op.create_foreign_key(None, 'cantones', 'provincias', ['id_provincias'], ['id'])
    op.drop_column('cantones', 'provincias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cantones', sa.Column('provincias', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cantones', type_='foreignkey')
    op.create_foreign_key('cantones_provincias_fkey', 'cantones', 'provincias', ['provincias'], ['id'])
    op.drop_column('cantones', 'id_provincias')
    # ### end Alembic commands ###
