"""empty message

Revision ID: e3db50fe68da
Revises: 5a2fd1cf892b
Create Date: 2024-01-03 18:50:09.995527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3db50fe68da'
down_revision = '5a2fd1cf892b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relese_date', sa.String(length=80), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('poster',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=3000),
               existing_nullable=False)
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.alter_column('poster',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('relese_date')

    # ### end Alembic commands ###
