"""Agrega campo ubicacion a Evento

Revision ID: e4757bdef421
Revises: 0777d42c751e
Create Date: 2025-05-27 16:30:24.962745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4757bdef421'
down_revision = '0777d42c751e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('creador_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ubicacion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('fecha')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('ubicacion',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('creador_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
