"""empty message

Revision ID: eb64f5493750
Revises: 1092a6a6d1d1
Create Date: 2025-10-17 17:45:56.043460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb64f5493750'
down_revision = '1092a6a6d1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('assign_doctor',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('assign_doctor',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
