"""empty message

Revision ID: ef02e5ef8fa8
Revises: 21f5540bab2c
Create Date: 2025-09-20 18:47:08.506715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef02e5ef8fa8'
down_revision = '21f5540bab2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('airbnb_checkin',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('airbnb_checkout',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('reservation_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.alter_column('airbnb_guestpic_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_booking_listing_googleid'), type_='unique')
        batch_op.drop_constraint(batch_op.f('bookings_listing_id_fkey'), type_='foreignkey')
        batch_op.drop_column('airbnb_guestpic')
        batch_op.drop_column('phone_last4')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_constraint(batch_op.f('listings_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('booking_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('airbnb_address')
        batch_op.drop_column('airbnb_zipcode')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('security_question')
        batch_op.drop_column('jpeg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jpeg', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('security_question', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airbnb_zipcode', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('airbnb_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('listings_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('image_url')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('street')
        batch_op.drop_column('name')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_last4', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('airbnb_guestpic', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('bookings_listing_id_fkey'), 'listings', ['listing_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('uq_booking_listing_googleid'), ['listing_id', 'google_calendar_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('airbnb_guestpic_url',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('reservation_url',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('airbnb_checkout',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('airbnb_checkin',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
