"""empty message

Revision ID: ef62170ac27a
Revises: a80adf762444
Create Date: 2023-12-16 21:45:27.152713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef62170ac27a'
down_revision = 'a80adf762444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.drop_constraint('publicacion_email_key', type_='unique')
        batch_op.drop_constraint('publicacion_fecha_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacion', schema=None) as batch_op:
        batch_op.create_unique_constraint('publicacion_fecha_key', ['fecha'])
        batch_op.create_unique_constraint('publicacion_email_key', ['email'])

    # ### end Alembic commands ###
