"""empty message

Revision ID: ef636c93dd66
Revises: d88cbc8c710f
Create Date: 2025-04-18 10:24:50.107794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef636c93dd66'
down_revision = 'd88cbc8c710f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))
        batch_op.drop_column('image_logo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
