"""empty message

<<<<<<<< HEAD:migrations/versions/337453297e05_.py
Revision ID: 337453297e05
Revises: 
Create Date: 2025-07-30 16:51:35.189918
========
Revision ID: fbb6c118dad2
Revises: 
Create Date: 2025-07-30 16:57:05.866068
>>>>>>>> develop:migrations/versions/fbb6c118dad2_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/337453297e05_.py
revision = '337453297e05'
========
revision = 'fbb6c118dad2'
>>>>>>>> develop:migrations/versions/fbb6c118dad2_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=27), nullable=False),
    sa.Column('sueldo', sa.Float(), nullable=False),
    sa.Column('is_student', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('gasto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('emoji', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=255), nullable=True),
    sa.Column('enlace', sa.String(length=255), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad_meta', sa.Float(), nullable=False),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objetivo')
    op.drop_table('link')
    op.drop_table('gasto')
    op.drop_table('user')
    op.drop_table('articulo')
    # ### end Alembic commands ###
