"""empty message

Revision ID: fe1532a7ae5d
Revises: dc1fd256366d
Create Date: 2021-05-05 03:59:49.085399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1532a7ae5d'
down_revision = 'dc1fd256366d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyme', sa.Column('Imagen', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyme', 'Imagen')
    # ### end Alembic commands ###
