"""empty message

Revision ID: fff8160df218
Revises: 84f722ac7a60
Create Date: 2023-12-14 04:53:23.722054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff8160df218'
down_revision = '84f722ac7a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('monday_start', sa.String(length=10), nullable=True),
    sa.Column('monday_end', sa.String(length=10), nullable=True),
    sa.Column('tuesday_start', sa.String(length=10), nullable=True),
    sa.Column('tuesday_end', sa.String(length=10), nullable=True),
    sa.Column('wednesday_start', sa.String(length=10), nullable=True),
    sa.Column('wednesday_end', sa.String(length=10), nullable=True),
    sa.Column('thursday_start', sa.String(length=10), nullable=True),
    sa.Column('thursday_end', sa.String(length=10), nullable=True),
    sa.Column('friday_start', sa.String(length=10), nullable=True),
    sa.Column('friday_end', sa.String(length=10), nullable=True),
    sa.Column('saturday_start', sa.String(length=10), nullable=True),
    sa.Column('saturday_end', sa.String(length=10), nullable=True),
    sa.Column('sunday_start', sa.String(length=10), nullable=True),
    sa.Column('sunday_end', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('program_number')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('programs')
    # ### end Alembic commands ###
